"""Database helpers for analytical macro/surendettement queries."""

from __future__ import annotations

import sqlite3
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterator

from sqlalchemy import create_engine, inspect, text
from sqlalchemy.engine import Connection

from app.core.config import settings


@contextmanager
def analytics_connection(
    db_path: str | None = None,
) -> Iterator[sqlite3.Connection | Connection]:
    if settings.ANALYTICS_DATABASE_URL and db_path is None:
        engine = create_engine(settings.ANALYTICS_DATABASE_URL, future=True)
        with engine.begin() as connection:
            ensure_override_table(connection)
            yield connection
        engine.dispose()
        return
    path = Path(db_path or settings.ANALYTICS_DB_PATH)
    if not path.exists():
        raise FileNotFoundError(f"Analytics database not found: {path}")
    sqlite_connection = sqlite3.connect(path)
    sqlite_connection.row_factory = sqlite3.Row
    sqlite_connection.execute("PRAGMA foreign_keys = ON")
    try:
        ensure_override_table(sqlite_connection)
        yield sqlite_connection
        sqlite_connection.commit()
    finally:
        sqlite_connection.close()


def ensure_override_table(connection: sqlite3.Connection | Connection) -> None:
    if isinstance(connection, Connection):
        connection.execute(
            text(
                """
                CREATE TABLE IF NOT EXISTS fact_macro_override (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    period_key VARCHAR(16) NOT NULL,
                    reference_year INTEGER NOT NULL,
                    departement_code VARCHAR(16) NOT NULL,
                    indicator_key VARCHAR(255) NOT NULL,
                    indicator_code VARCHAR(255) NOT NULL,
                    indicator_name TEXT,
                    indicator_group TEXT,
                    value DOUBLE PRECISION NOT NULL,
                    source_note TEXT,
                    created_at VARCHAR(64) NOT NULL,
                    updated_at VARCHAR(64) NOT NULL
                )
                """
            )
        )
        connection.execute(
            text(
                """
                CREATE INDEX IF NOT EXISTS idx_macro_override_lookup
                ON fact_macro_override(
                    period_key, departement_code, indicator_key
                )
                """
            )
        )
        return
    conformed = all(
        connection.execute(
            "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
            (table,),
        ).fetchone()
        for table in ("dim_period", "dim_department", "dim_indicator")
    )
    if not conformed:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS fact_macro_override (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                reference_year INTEGER NOT NULL,
                departement_code TEXT NOT NULL,
                indicator_code TEXT NOT NULL,
                indicator_name TEXT,
                indicator_group TEXT,
                value REAL NOT NULL,
                source_note TEXT,
                created_at TEXT NOT NULL,
                updated_at TEXT NOT NULL
            )
            """
        )
        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS idx_macro_override_lookup
            ON fact_macro_override(
                reference_year, departement_code, indicator_code
            )
            """
        )
        return
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS fact_macro_override (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            period_key TEXT NOT NULL,
            reference_year INTEGER NOT NULL,
            departement_code TEXT NOT NULL,
            indicator_key TEXT NOT NULL,
            indicator_code TEXT NOT NULL,
            indicator_name TEXT,
            indicator_group TEXT,
            value REAL NOT NULL,
            source_note TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            FOREIGN KEY(period_key) REFERENCES dim_period(period_key),
            FOREIGN KEY(departement_code)
                REFERENCES dim_department(departement_code),
            FOREIGN KEY(indicator_key) REFERENCES dim_indicator(indicator_key)
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_macro_override_lookup
        ON fact_macro_override(period_key, departement_code, indicator_key)
        """
    )


def fetch_all(
    connection: sqlite3.Connection | Connection,
    query: str,
    params: dict[str, Any] | None = None,
) -> list[dict]:
    if isinstance(connection, Connection):
        return [
            dict(row)
            for row in connection.execute(text(query), params or {}).mappings()
        ]
    rows = connection.execute(query, params or {}).fetchall()
    return [dict(row) for row in rows]


def fetch_one(
    connection: sqlite3.Connection | Connection,
    query: str,
    params: dict[str, Any] | None = None,
) -> dict | None:
    if isinstance(connection, Connection):
        row = connection.execute(text(query), params or {}).mappings().first()
    else:
        row = connection.execute(query, params or {}).fetchone()
    return dict(row) if row else None


def execute(
    connection: sqlite3.Connection | Connection,
    query: str,
    params: dict[str, Any] | None = None,
):
    if isinstance(connection, Connection):
        return connection.execute(text(query), params or {})
    return connection.execute(query, params or {})


def table_columns(
    connection: sqlite3.Connection | Connection, table_name: str
) -> set[str]:
    if isinstance(connection, Connection):
        return {column["name"] for column in inspect(connection).get_columns(table_name)}
    return {
        row["name"]
        for row in connection.execute(f"PRAGMA table_info({table_name})")
    }


def database_objects(connection: sqlite3.Connection | Connection) -> list[str]:
    if isinstance(connection, Connection):
        inspector = inspect(connection)
        return sorted(inspector.get_table_names() + inspector.get_view_names())
    return [
        row["name"]
        for row in connection.execute(
            "SELECT name FROM sqlite_master "
            "WHERE type IN ('table', 'view') ORDER BY name"
        )
    ]


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()
